### ISSUE TITLE
Support Cloud Asset upload

### ISSUE THREAD

**Issue by ben181231** [SkygearIO/skygear-server#107]
### Tasks for Skygear-Server
- [x] Load config from env.
- [x] Request for signer token
- [x] Refresh signer token periodically
- [x] New endpoint `asset:put` for new upload protocol

### Tasks for SDKs
- [x] Support on iOS SDK
- [x] Support on JS SDK
- ~~Support on Android SDK~~

### Tasks for Others
- [ ] Update documentation

**Comment by rickmak** [comment]
Pending: ASSET_STORE_HOST should default to HOST if not specific explicitly.
