### ISSUE TITLE
Provide a way to query current user roles

### ISSUE THREAD

**Issue by rickmak** [SkygearIO/skygear-server#111]
Unable to get currentUser's roles when I logged in as non-Admin user. Would please advise?

- Skygear Server Date/Version: v0.14.0
- Application Platform: skygeario.com deployment.
- [ ] Is this a regression?
- [ ] Attached logs, screenshots

#### Expected Results

Current user can query his own roles by using `user:query`.

#### Actual Results

After I logged in as an Admin user, I can:
• run getUsersByEmail on currentUser's email
• run getUsersByEmail on other users' emails
=> It suits my needs when I logged in as Admin.

But after I logged in as an non-Admin user, I *cannot*:
• run getUsersByEmail on currentUser's email
• run getUsersByEmail on other users' emails
The response says:
`{"error":{"name":"PermissionDenied","code":102,"message":"No permission to query user"}}` with 403 status code.

#### Proposed solution

Instead of introducing complex access control to `user:query`. I would suggest provide an interface `me` that will return the current user auth data n and user record. It can be also act as an endpoint that validate the current access token validity before making others API call. In SDK, provided respective API.

For JS, I propose:

```
skygear.whoami()
```

Also `auth:login` will provided the user roles as in `me` too.

**Comment by ben181231** [comment]
### Tasks

- [ ] Add `user:me` endpoint and include roles in the response
- [ ] Add roles to auth (login / signup) response
- [ ] Add supports on **iOS SDK**
- [ ] Add supports on **Android SDK**
- [ ] Add supports on **Javascript SDK**
