### ISSUE TITLE
Auth UI tracking issue

### ISSUE THREAD

**Issue by louischan-oursky** [SkygearIO/skygear-server#1210]
Issues:

- [ ] [Update session mechanism](https://github.com/SkygearIO/skygear-server/issues/1241)
  - [x] [Refactor session mechanism](https://github.com/SkygearIO/skygear-server/pull/1244)
  - [x] [Fix session mechanism](https://github.com/SkygearIO/skygear-server/pull/1264)
  - [ ] [Make client optional in authentication](https://github.com/SkygearIO/skygear-server/pull/1265)
- [x] [Refactor API Key mechanism](https://github.com/SkygearIO/skygear-server/issues/1256)
  - [x] [Refactor API key mechanism](https://github.com/SkygearIO/skygear-server/pull/1259)
- [x] [Refactor authentication session mechanism](https://github.com/SkygearIO/skygear-server/issues/1253)
  - [x] [Refactor authentication mechanism](https://github.com/SkygearIO/skygear-server/pull/1262)
- [x] [Update AppConfiguration](https://github.com/SkygearIO/skygear-server/issues/1242)
  - [x] [Update AppConfiguration](https://github.com/SkygearIO/skygear-server/pull/1243)
- [x] [Update gateway to route by reading domain assignment](https://github.com/SkygearIO/skygear-server/issues/1245)
    - [x] [Domain assignment routing](https://github.com/SkygearIO/skygear-server/pull/1247)
- [ ] [Update gateway call auth resolve endpoint](https://github.com/SkygearIO/skygear-server/issues/1246)
- [x] [Refactor Authentication and SSO](https://github.com/SkygearIO/skygear-server/issues/1249)
  - [x] [Refactor authentication and SSO](https://github.com/SkygearIO/skygear-server/pull/1254)
- [x] [Store OIDC `nonce` in `state`](https://github.com/SkygearIO/skygear-server/issues/1250)
  - [x] [Store `nonce` in `state`](https://github.com/SkygearIO/skygear-server/pull/1251)
- [ ] [Update controller migration to use source in skygear-server](https://github.com/oursky/skygear-controller/issues/254)
- [ ] [Custom domain support assignment](https://github.com/oursky/skygear-controller/issues/255)
- [ ] [Unbreak controller with Auth UI update](https://github.com/oursky/skygear-controller/issues/257)
- [ ] [Unbreak path-only hook URL](https://github.com/SkygearIO/skygear-server/issues/1260)
- [ ] [Auth UI Web App](https://github.com/SkygearIO/skygear-server/issues/1261)
  - [x] [Auth UI Web App - Part 1](https://github.com/SkygearIO/skygear-server/pull/1263)
  - [ ] [Auth UI Web App - Part 2](https://github.com/SkygearIO/skygear-server/pull/1267)

PRs:

- [x] [Add CountryCallingCodes constant](https://github.com/SkygearIO/skygear-server/pull/1226)
- [x] [Extract server listen](https://github.com/SkygearIO/skygear-server/pull/1227)
- [x] [Deploy static asset to S3 bucket](https://github.com/SkygearIO/skygear-server/pull/1228)
- [x] [Move UpdateCookie](https://github.com/SkygearIO/skygear-server/pull/1229)
- [x] [Delete anonymous principal](https://github.com/SkygearIO/skygear-server/pull/1230)
- [x] [Refactor template engine](https://github.com/SkygearIO/skygear-server/pull/1231)
- [x] [Setup wire](https://github.com/SkygearIO/skygear-server/pull/1232)
- [x] [Remove server](https://github.com/SkygearIO/skygear-server/pull/1234)
- [x] [Remove custom token](https://github.com/SkygearIO/skygear-server/pull/1237)
- [x] [Authenticated request no longer require API key](https://github.com/SkygearIO/skygear-server/pull/1238)
- [x] [Move controller migration to skygear-server](https://github.com/SkygearIO/skygear-server/pull/1240)
- [x] [Remove audit trail](https://github.com/SkygearIO/skygear-server/pull/1248)
