### ISSUE TITLE
Forget password discussion

### ISSUE THREAD

**Issue by david90** [SkygearIO/skygear-server#134]

**Comment by royuen** [comment]
Discussion 5 Sept
- Support a special template in cloud code, if not provided, generate a standard forgot password and send to end user
- Support custom domain, need to update explanation text / doc to tell user how to update SPF / Domain Key
- Support in Plugin / Core (need to further decide)
- Support in SDK like ```User.forgetPassword("[email]")``` and the email will be sent to the user 
- If the application is self hosted, need to update env var to make it send from sendmail

**Comment by cheungpat** [comment]
## Tasks

- [ ] add `--load-plugins`/`LOAD_PLUGINS=` to py-skygear, load modules before loading
  cloudcode
  - name of the plugin is the same as the python module
  - load modules defined in cloudcode directory first, then system modules
- [ ] redefined lambda/handler should overrride previous defined ones
- [ ] adapt forgot password functionality from other projects
  - Read `SMTP_HOST`, `SMTP_USER`, `SMTP_PASS` env var for sending outgoing mails
  - Read `SMTP_MAILFROM` env var for specifying email "from" address
  - Included in py-skyear package (loaded in cloud by default, not loaded in development by default)
- [ ] cloud deploy: scheduler to add SMTP credentials to deployed apps envvars

## How plugins loading works

Add `--load-plugins` to py-skygear which loads python modules before
loading developer's cloudcode.

```
py-skygear --load-plugins forgot_password[,...] [__init__.py]
# or 
LOAD_PLUGINS="forgot_password[,...]" py-skygear [__init__.py]
```

Where the name of the plugin is the name of the python module to be loaded. The order to locate the module is:

1. module in cloudcode directory is loaded first
2. system-installed modules

i.e. developer can override system provided `forgot_password` plugin by providing its own `forgot_password` plugin in cloudcode

The `--load-plugins` option is set when building cloudcode and running cloudcode.

@rickmak @royuen please leave some comments, this issue should belongs to py-skygear because it is not implemented in the core

**Comment by rickmak** [comment]
We do not need the `--load-plugins`.
We can make this work. `py-skygear [forgot_password] [yet_another_floder_name] [another_installed_python_package] [__init__.py]`


So in local development, if the developer want to include the forgot_password plugin he/she will do the following:
- `git submodule add https://github.com/SkygearIO/forgot_password.git forgot_password `
- Modify the docker-compose.yml plugin section command to `py-skygear forgot_password __init__.py`

**Comment by cheungpat** [comment]
> We do not need the --load-plugins.

Can’t see why we can’t have that. And the library to parse env variable is the same library to define command options, so we have that for free.

> py-skygear [forgot_password] [yet_another_floder_name] [another_installed_python_package] [__init__.py]

In the above scenario (`py-skygear forgot_password yet_another_floder_name another_installed_python_package __init__.py`), we will attempt to load four package/files. How about (`py-skygear forgot_password`) will we only load `forgot_password` and not `__init__.py`?

> `git submodule add https://github.com/SkygearIO/forgot_password.git forgot_password`

This command is not needed if we will include it in `py-skygear`. Alternatively, I don’t mind `forgot_password` is outside `py-skygear`.

**Comment by cheungpat** [comment]
I am going to file issues in py-skygear and close this issue (which is in skygear-server)
