### ISSUE TITLE
Add API to unset device token

### ISSUE THREAD

**Issue by royuen** [SkygearIO/skygear-server#249]
### Tasks

- [x] add `device:unregister` endpoint
- [ ] Update iOS SDK
- [x] Update Android SDK
- [x] Update JS SDK
