### ISSUE TITLE
Server may becomes unresponding with database hooks and recursive send_action

### ISSUE THREAD

**Issue by cheungpat** [SkygearIO/skygear-server#281]
* [x] a fix for breaking long wait between server and plugin #271 
* [x] abort database operation when timeout #277 
* [x] bidirectional plugin transport and multiplexing #295

**Comment by cheungpat** [comment]
a new image is pushed to staging cloud which has support for #271

**Comment by cheungpat** [comment]
# Bidirectional plugin transport and multiplexing

The current plugin transport only support communication initiated from the server side of the transport. 

There is an existing mechanism for the plugin to make request to the server just like a normal client by making http request through request router. This mechanism is often referred to as `send_action` named after the python function with the same name.

It is proposed that we should implement bidirectional plugin transport so that plugin-initiated request are made through the plugin transport instead. Multiplexing refers to how transport route communication among workers.

## Benefits for implementing bidirectional plugin transport and multiplexing

* easier configuration - while transport may require extra config for bidirectional communication, no config is necessary for api key, master key and server endpoint.
* reduced overhead - imitating a client request requires the plugin to make extra http connection, which is extra overhead when using zmq transport.
* tracking request lifecycle - keep track of control flow across process boundary (to support better logging).
* reuse blocked workers - control flow can be handed off to the blocked worker if the blocked worker is handling the same request.

## Implementation approach

* (existing behavior) plugin runtime register a new worker for each thread
* transport keep track of context when sending message across process boundary
* transport to increment call stack when crossing process boundary
* when call-stack=0, select a free worker from pool, worker is no longer in the pool for other requests
* call-stack++ and send message to worker
* worker may call server code (new behavior), two options here (see below)
* call-stack++ when receiving message from worker that will call other server code
* when call-stack=2, re-use the same worker previously selected, use request unique ID to find the worker
* when plugin code returns data (i.e. not calling other server code) call-stack is decremented
* when call-stack=0, the worker is marked free and put back to pool

### ZMQ Transport protocol options

Option 1: Overload the current ZMQ transport protocol design in that plugin code calls server code by using the response message, the server code returns data by using the request message.

This option is less intrusive to the overall ZMQ transport protocol design. The semantic maybe convoluted.

Option 2: Add a new kind of message in the ZMQ transport protocol design so that plugin code calls server code by using a new kind of request message, and the server code returns data by using a new kind of response message.

The semantic is easier to understand.

### HTTP Transport protocol options

We have to decide whether multiplexing makes sense in HTTP transport, this is because send_action is inherently HTTP-based.

If we want HTTP transport to support multiplexing, the transport will expose a http endpoint for the plugin to call server-side code.

**Comment by cheungpat** [comment]
@b123400

**Comment by b123400** [comment]
- [x] [Golang] Try to send a dummy message after a new request, before receiving the response 
- [ ] [Python] Try to catch that message
- [ ] [Python] Look at the normal http transport
- [ ] [Python] Modify api calling Golang to use zmq
- [ ] [Python] Embed HTTP request body into zmq message, with worker id
- [ ] [Golang] Send back the worker id in response
- [ ] [Python] Ask the worker to handle the response
  - Make worker works in something like generator / co-routine?
- [ ] [Golang] Add a stack count
  - Set a maximum and throw error when exceeded

**Comment by cheungpat** [comment]
@b123400 thanks for coming up with a list, i couldn’t have came up with the list myself

but i think we need to talk about it so we are on the same page

I’d like to address this specific point:

> Embed HTTP request body into zmq message, with worker id

One of the design decision early on is that the Skygear request router is designed in a way that it does not necessarily have HTTP semantics. When we are going to implement bidirectional communication, I think we can make use of this design so that you do not need to wrap `send_action` in a HTTP request payload before sending from the plugin to the server.

**Comment by cheungpat** [comment]
i am going to make a new issue because this issue is supposed to be a meta-issue. sorry about that

**Comment by cheungpat** [comment]
#295

**Comment by chpapa** [comment]
@cheungpat @rickmak which stage this issue should be in? It's now "in review"
